// Access class of every API handler, keyed by repo-relative file path.
// The route-access harness uses it to hit each route with no session and with forged identity keys
// (clerk_id, user_id, ...) in the query, body and headers:
//   user, admin, organizer, admin_or_organizer -> 401 without a session
//   admin                                      -> 403 for a signed-in non-admin
//   optional                                   -> public, but personalised when a session exists
//   cron                                       -> 401 without `Authorization: Bearer <CRON_SECRET>`, whatever the session
// server/api/auth/[...all].ts is Better Auth's own handler and is not listed.

export type Access = 'public' | 'optional' | 'user' | 'admin' | 'organizer' | 'admin_or_organizer' | 'cron'

export const ROUTE_ACCESS: Record<string, Access> = {
  'server/api/admin/categories/[id].delete.ts': 'admin',
  'server/api/admin/categories/[id].put.ts': 'admin',
  'server/api/admin/categories/index.get.ts': 'admin',
  'server/api/admin/categories/index.post.ts': 'admin',
  'server/api/admin/categories/reorder.post.ts': 'admin',
  'server/api/admin/check.get.ts': 'admin',
  'server/api/admin/city-segments/[id].delete.ts': 'admin',
  'server/api/admin/city-segments/[id].put.ts': 'admin',
  'server/api/admin/city-segments/[id]/cities.delete.ts': 'admin',
  'server/api/admin/city-segments/[id]/cities.post.ts': 'admin',
  'server/api/admin/city-segments/index.get.ts': 'admin',
  'server/api/admin/city-segments/index.post.ts': 'admin',
  'server/api/admin/debug/api-key.get.ts': 'admin',
  'server/api/admin/fix-win-streaks.post.ts': 'admin',
  'server/api/admin/invitations.get.ts': 'admin',
  'server/api/admin/invitations/[id].delete.ts': 'admin',
  'server/api/admin/invitations/[id]/resend.post.ts': 'admin',
  'server/api/admin/matches.get.ts': 'admin',
  'server/api/admin/matches/fallback.get.ts': 'admin',
  'server/api/admin/matches/process-missing-rating-history.post.ts': 'admin',
  'server/api/admin/matches/recalculate.post.ts': 'admin',
  'server/api/admin/matches/reprocess-fallback.post.ts': 'admin',
  'server/api/admin/moderation/messages.get.ts': 'admin',
  'server/api/admin/moderation/messages/[id].post.ts': 'admin',
  'server/api/admin/organizers/[id].delete.ts': 'admin',
  'server/api/admin/organizers/[id].put.ts': 'admin',
  'server/api/admin/organizers/index.get.ts': 'admin',
  'server/api/admin/organizers/index.post.ts': 'admin',
  'server/api/admin/pending-players.get.ts': 'admin',
  'server/api/admin/pending-players/[id].delete.ts': 'admin',
  'server/api/admin/pending-players/[id]/resend.post.ts': 'admin',
  'server/api/admin/pending-players/invite.post.ts': 'admin',
  'server/api/admin/players.get.ts': 'admin',
  'server/api/admin/players/[id].delete.ts': 'admin',
  'server/api/admin/players/[id].put.ts': 'admin',
  'server/api/admin/players/[id]/restore.post.ts': 'admin',
  'server/api/admin/rankings/decay.get.ts': 'admin',
  'server/api/admin/rankings/decay/[id].post.ts': 'admin',
  'server/api/admin/rankings/health.get.ts': 'admin',
  'server/api/admin/rankings/leaderboards.get.ts': 'admin',
  'server/api/admin/rankings/matches/[id]/impact.get.ts': 'admin',
  'server/api/admin/rankings/placement.get.ts': 'admin',
  'server/api/admin/rankings/placement/[id].put.ts': 'admin',
  'server/api/admin/rankings/players/[id].get.ts': 'admin',
  'server/api/admin/rankings/stats.get.ts': 'admin',
  'server/api/admin/rankings/trends.get.ts': 'admin',
  'server/api/admin/rankings/update-previous-ranks.post.ts': 'admin',
  'server/api/admin/stats.get.ts': 'admin',
  'server/api/admin/tournaments/[id].delete.ts': 'admin',
  'server/api/admin/tournaments/[id].get.ts': 'admin',
  'server/api/admin/tournaments/[id].put.ts': 'admin',
  'server/api/admin/tournaments/[id]/generate-brackets.post.ts': 'admin',
  'server/api/admin/tournaments/[id]/group-deadline.put.ts': 'admin',
  'server/api/admin/tournaments/[id]/matches.get.ts': 'admin',
  'server/api/admin/tournaments/[id]/playoff-deadline.put.ts': 'admin',
  'server/api/admin/tournaments/[id]/recalculate-standings.post.ts': 'admin',
  'server/api/admin/tournaments/[id]/register.post.ts': 'admin',
  'server/api/admin/tournaments/[id]/unscheduled-matches.get.ts': 'admin',
  'server/api/admin/tournaments/[id]/withdraw.post.ts': 'admin',
  'server/api/admin/tournaments/index.get.ts': 'admin',
  'server/api/admin/tournaments/index.post.ts': 'admin',
  'server/api/categories.get.ts': 'public',
  'server/api/cron/monthly-decay.get.ts': 'cron',
  'server/api/cities.get.ts': 'public',
  'server/api/invitations/accept.post.ts': 'user',
  'server/api/leaderboard/index.get.ts': 'optional',
  'server/api/leaderboard/nearby.get.ts': 'public',
  'server/api/leaderboard/top.get.ts': 'public',
  'server/api/matches/[id].get.ts': 'user',
  'server/api/matches/[id].put.ts': 'user',
  'server/api/matches/[id]/calculate-elo.post.ts': 'admin',
  'server/api/matches/[id]/messages.get.ts': 'user',
  'server/api/matches/[id]/messages.post.ts': 'user',
  'server/api/matches/[id]/rating-history.get.ts': 'user',
  'server/api/matches/index.get.ts': 'user',
  'server/api/matches/index.post.ts': 'user',
  'server/api/matchmaking/recommendations.get.ts': 'user',
  'server/api/notifications/[id]/dismiss.post.ts': 'user',
  'server/api/notifications/[id]/read.post.ts': 'user',
  'server/api/notifications/mark-all-read.post.ts': 'user',
  'server/api/notifications/pending.get.ts': 'user',
  'server/api/organizer/tournaments/[id].delete.ts': 'organizer',
  'server/api/organizer/tournaments/[id].get.ts': 'organizer',
  'server/api/organizer/tournaments/[id].put.ts': 'organizer',
  'server/api/organizer/tournaments/[id]/advance-phase.post.ts': 'organizer',
  'server/api/organizer/tournaments/[id]/generate-brackets.post.ts': 'organizer',
  'server/api/organizer/tournaments/[id]/generate-playoffs.post.ts': 'organizer',
  'server/api/organizer/tournaments/[id]/group-deadline.put.ts': 'organizer',
  'server/api/organizer/tournaments/[id]/phase-status.get.ts': 'organizer',
  'server/api/organizer/tournaments/[id]/players.search.get.ts': 'organizer',
  'server/api/organizer/tournaments/[id]/playoff-deadline.put.ts': 'organizer',
  'server/api/organizer/tournaments/[id]/recalculate-standings.post.ts': 'organizer',
  'server/api/organizer/tournaments/[id]/register.post.ts': 'organizer',
  'server/api/organizer/tournaments/[id]/unscheduled-matches.get.ts': 'organizer',
  'server/api/organizer/tournaments/[id]/update-bracket.post.ts': 'organizer',
  'server/api/organizer/tournaments/index.get.ts': 'organizer',
  'server/api/organizer/tournaments/index.post.ts': 'organizer',
  'server/api/pending-players/[id].get.ts': 'public',
  'server/api/pending-players/index.post.ts': 'user',
  'server/api/pending-players/invitation/[token].get.ts': 'public',
  'server/api/players/[id].get.ts': 'public',
  'server/api/players/[id].put.ts': 'user',
  'server/api/players/[id]/decay-status.get.ts': 'public',
  'server/api/players/[id]/head-to-head/[opponentId].get.ts': 'public',
  'server/api/players/[id]/matches.get.ts': 'public',
  'server/api/players/[id]/ranking-position.get.ts': 'public',
  'server/api/players/[id]/rating-history.get.ts': 'public',
  'server/api/players/[id]/tier-progress.get.ts': 'public',
  'server/api/players/level-suggestion.get.ts': 'user',
  'server/api/players/level-suggestion.post.ts': 'user',
  'server/api/players/me.get.ts': 'user',
  'server/api/players/me.post.ts': 'user',
  'server/api/players/search.get.ts': 'public',
  'server/api/rankings/index.get.ts': 'public',
  'server/api/tournaments/[id].get.ts': 'public',
  'server/api/tournaments/[id]/bracket.get.ts': 'public',
  'server/api/tournaments/[id]/group/[groupId]/matches.get.ts': 'public',
  'server/api/tournaments/[id]/register.post.ts': 'user',
  'server/api/tournaments/index.get.ts': 'public',
  'server/api/tournaments/past.get.ts': 'public',
}
