// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
  // NOTE: shadowDatabaseUrl is not yet in PrismaConfig typings.
  // It is still supported at runtime, so we cast the config to any.
  // Disable shadow database to avoid advisory lock issues with Supabase.
  // This skips migration validation but allows migrations to run.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
});
